# Generated by Django 6.0.8 on 2026-09-06 06:49

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0006_alter_libraryattachment_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('library.libraryitem',),
        ),
    ]
